#ifndef COUNT_DIAGONALS_PARALLEL_TO_SECONDARY_WITHOUT_ZERO_H
#define COUNT_DIAGONALS_PARALLEL_TO_SECONDARY_WITHOUT_ZERO_H

size_t countDiagonalsParallelToSecondaryWithoutZero(const int* matrix, size_t rows);

#endif
